/*1)CREATE 5 TABLES(show_room, chat_center, temple_info,
market_info, metro_info) with 10 columns.
2)apply 2 not null, 2 unique, 2 check constraints.
3)insert 20 data for each table.
4) apply 1 not null using alter. 1 unique , 2 check constraints using alter command.*/

CREATE DATABASE ASSIGNMENT4;

USE ASSIGNMENT4;
CREATE TABLE show_room(ID INT,S_NAME VARCHAR(30),S_MAINTANANCE VARCHAR(20),S_NO_OF_ITEM INT,S_ITEM_NAME VARCHAR(20),S_NO_BOOK INT,S_NO_BOOK_NAME VARCHAR(30),S_BOOK_SERIAL_NO BIGINT,S_ROOM_NO INT,S_ROOM_NAME VARCHAR(30));
DESC show_room;
SELECT * FROM show_room;

CREATE TABLE chat_center(ID INT,CHAT_NAME VARCHAR(20),CHAT_LOC VARCHAR(30),NO_OF_CHATS INT,CHAT_USER_NAME VARCHAR(30),CHAT_OWNER_NAME VARCHAR(30),CHAT_INGRIDIENTS_NAME VARCHAR(20),CHAT_LOC_PINCODE BIGINT,CHAT_TIMING TIME,CHAT_MAINTENANCE VARCHAR(30));
DESC chat_center;

CREATE TABLE temple_info(ID INT,TEMP_NAME VARCHAR(30),TEMP_LOC VARCHAR(30),TEMP_CREATED_YEAR YEAR,TEMP_STRAT_TIMING TIME,TEMP_CREATED_BY VARCHAR(20));
DESC temple_info;

CREATE TABLE market_info(ID INT,M_NAME VARCHAR(30),M_LOC VARCHAR(30),M_ITEAM VARCHAR(30),M_DATA VARCHAR(30),M_OWNER_NAME VARCHAR(20),M_SERIAL_NO INT,M_LOC_PINCODE BIGINT);
DESC market_info;

CREATE TABLE metro_info(ID INT,M_NAME VARCHAR(20),M_BLUELINE_AREA VARCHAR(20),M_GREENLINE_AREA VARCHAR(30),M_PURPULELINE_AREA VARCHAR(30),M_YELLOWLINE_AREA VARCHAR(30),M_PINKLINE_AREA VARCHAR(30),M_ORANGELINE_AREA VARCHAR(30),M_TIMING TIME,M_MAIN_STATION VARCHAR(30));
DESC metro_info;

INSERT INTO show_room VALUES(1,'REST ROOM','GOOD',30,'BOOK',50,'MAHABARATHA',23465,89,'SHARAVATHI');
INSERT INTO show_room VALUES(2,'REST ROOM','GOOD',45,'BOOK',45,'MAHABARATHA',1234,33,'GANGA');
INSERT INTO show_room VALUES(3,'REST ROOM','GOOD',76,'BOOK',23,'MAHABARATHA',8678,45,'KAVERI');
INSERT INTO show_room VALUES(4,'REST ROOM','GOOD',45,'TABLE',23,'TREE TABLE',65567,687,'BHADRA');
INSERT INTO show_room VALUES(5,'REST ROOM','BAD',98,'BOOK',54,'MAHABARATHA',6745,8,'SHARAVATHI');
INSERT INTO show_room VALUES(6,'REST ROOM','GOOD',78,'BOOK',77,'MAHABARATHA',2355,456,'SHARAVATHI');
INSERT INTO show_room VALUES(7,'REST ROOM','GOOD',23,'TABLE',45,'TREE TABLE',565,43,'MEGHALAYA');
INSERT INTO show_room VALUES(8,'REST ROOM','BAD',12,'BOOK',32,'MAHABARATHA',446,78,'SHARAVATHI');
INSERT INTO show_room VALUES(9,'REST ROOM','GOOD',11,'BOOK',23,'MAHABARATHA',1345,54,'CHIKAMAGALURU');
INSERT INTO show_room VALUES(10,'REST ROOM','GOOD',45,'BOOK',48,'MAHABARATHA',345,23,'SHARAVATHI');
INSERT INTO show_room VALUES(11,'REST ROOM','GOOD',66,'BOOK',79,'MAHABARATHA',34878,55,'SHARAVATHI');
INSERT INTO show_room VALUES(12,'REST ROOM','BAD',44,'BOOK',78,'MAHABARATHA',1323,33,'SHARAVATHI');
INSERT INTO show_room VALUES(13,'REST ROOM','GOOD',33,'BOOK',65,'MAHABARATHA',67645,23,'MEGHALAYA');
INSERT INTO show_room VALUES(14,'REST ROOM','GOOD',25,'BOOK',87,'MAHABARATHA',46456,23,'SHARAVATHI');
INSERT INTO show_room VALUES(15,'REST ROOM','GOOD',76,'BOOK',23,'MAHABARATHA',2344,44,'HIMALAYA');
INSERT INTO show_room VALUES(16,'REST ROOM','BAD',87,'BOOK',34,'MAHABARATHA',34556,34,'SHARAVATHI');
INSERT INTO show_room VALUES(17,'REST ROOM','GOOD',56,'BOOK',34,'MAHABARATHA',4565,78,'JAMU');
INSERT INTO show_room VALUES(18,'REST ROOM','GOOD',34,'BOOK',24,'MAHABARATHA',788,56,'SHARAVATHI');
INSERT INTO show_room VALUES(19,'REST ROOM','GOOD',54,'BOOK',45,'MAHABARATHA',5678,89,'KASHMIR');
INSERT INTO show_room VALUES(20,'REST ROOM','GOOD',86,'BOOK',89,'MAHABARATHA',224,56,'SHARAVATHI');
